openapi: 3.2.0
info:
  title: Orbii IBA Ns API
  description: API for managing transactions, clients, and companies.
  version: 1.0.5-oas3
servers:
- url: https://api.orbii.ai
  description: Production server
tags:
- name: IBANs
paths:
  /ibans:
    get:
      summary: Get distinct IBANs
      description: Fetches all distinct IBANs.
      tags:
      - IBANs
      parameters:
      - name: user
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A list of distinct IBANs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      operationId: getIbans
      x-operation-id-source: derived
