openapi: 3.0.0
info:
  title: Orbii API - Foodics Business Category Assignment Categories API
  version: 1.0.2
  description: API for retrieving micro loan KPIs, scoring, risk assessment, band classification, and related data.
servers:
- url: https://api.foodics.orbii.ai/
  description: Production Server
tags:
- name: Categories
paths:
  /categories/{clientname}:
    get:
      summary: Get distinct categories for a client
      description: Fetches distinct categories for a given client.
      tags:
      - Categories
      parameters:
      - name: clientname
        in: path
        required: true
        schema:
          type: string
      - name: user
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A list of distinct categories for the client.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
