openapi: 3.0.0
info:
  title: Orbii API - Foodics Business Category Assignment Clients API
  version: 1.0.2
  description: API for retrieving micro loan KPIs, scoring, risk assessment, band classification, and related data.
servers:
- url: https://api.foodics.orbii.ai/
  description: Production Server
tags:
- name: Clients
paths:
  /clients:
    get:
      summary: Get all clients
      description: Fetches all clients.
      tags:
      - Clients
      parameters:
      - name: user
        in: query
        schema:
          type: string
      - name: password
        in: query
        schema:
          type: string
      responses:
        '200':
          description: A list of clients.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    clientname:
                      type: string
                    date_added:
                      type: string
                      format: date-time
                    customer_id:
                      type: string
  /clients/range:
    get:
      summary: Get clients added within a date range
      tags:
      - Clients
      parameters:
      - name: start_date
        in: query
        required: true
        schema:
          type: string
          format: date
        description: Start date (YYYY-MM-DD)
      - name: end_date
        in: query
        required: true
        schema:
          type: string
          format: date
        description: End date (YYYY-MM-DD)
      - name: user
        in: query
        required: false
        schema:
          type: string
        description: username
      - name: password
        in: query
        required: false
        schema:
          type: string
        description: password
      responses:
        '200':
          description: Array of clients within the range
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '400':
          description: Missing or invalid parameters
        '500':
          description: Server error
components:
  schemas:
    Client:
      type: object
      properties:
        clientname:
          type: string
        date_added:
          type: string
